# Generated by Django 3.2.6 on 2021-08-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210824_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='value',
            new_name='vote',
        ),
    ]
